volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  db:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "psql -U daniluk_admin -d backend  -c 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    env_file:
      - ../.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - db
    